language: clojure
lein: lein2
script:
  - lein2 install
  - lein2 with-profile +dev cloverage --coveralls
  - curl -F 'json_file=@target/coverage/coveralls.json' 'https://coveralls.io/api/v1/jobs'
jdk:
  - oraclejdk8